### ISSUE TITLE
Assertion Failure for specific read

### ISSUE THREAD

**Issue by EddieFerro** [maxrossi91/moni-align#20]
In calls to `compute_mapq_pe_bwa` (in mapq.hpp) from `paired_chain_orphan_score`, the line `assert(score2 <= score)` fails consistently with several reads. This causes a crash in debug mode. This issue occurs when building any dataset and should be reproducible with any VCF, reference, and set of reads. 
[GRCh38.8.HG002.mate.align.log](https://github.com/maxrossi91/moni-align/files/11870365/GRCh38.8.HG002.mate.align.log

**Comment by rvarki** [comment]
Fixed with #55
