### ISSUE TITLE
Crash during alignment step of Arabidopsis data

### ISSUE THREAD

**Issue by EddieFerro** [maxrossi91/moni-align#22]
During the alignment step, there is a crash with no discernible reference as to the cause of the crash. This crash occurs with any number of VCFs and any set of reads of Arabidopsis data. During the build step with this data, there is no error.

Running moni-align in debug mode, there are several assertion failures that occur and do not allow for the alignment step to continue to the point of the crash that occurs in release mode. The most promising is an assertion fail associated with "expandSubstr" from PlainSLP.hpp which is called by "orphan_fill" in aligner_ksw2.hpp.

The respective log files are attached.

[TAIR10.1.Seattle0.mate.align.log](https://github.com/maxrossi91/moni-align/files/12352819/TAIR10.1.Seattle0.mate.align.log)

**Comment by rvarki** [comment]
Should be resolved with #41
