### ISSUE TITLE
Edge case that causes crash in align function

### ISSUE THREAD

**Issue by rvarki** [maxrossi91/moni-align#33]
The edge case occurs in `fill_chain` when you try to align the full chain. The issue occurs when the MEM position in the reference is very close to the beginning (for example, say position 0) and the MEM position in the read is somewhere in the middle. 

https://github.com/maxrossi91/moni-align/blob/af3d3c2eb70afb413c9d6349e8b36076bb1b9686/include/aligner/aligner_ksw2.hpp#L2412

This will cause the ref_pos to become a very large number (since size_t is unsigned and cannot store negative numbers) which eventually causes a crash at this line 

https://github.com/maxrossi91/moni-align/blob/af3d3c2eb70afb413c9d6349e8b36076bb1b9686/include/aligner/aligner_ksw2.hpp#L2541

I am not sure how to correctly handle this case.

**Comment by maxrossi91** [comment]
You can test if `(lcs_len > 0 ? ez_lc.mqe_t + 1 : 0)` is greater than `mem_pos`, and if not set the result to `0`. Maybe soft/hard clip the left bases of the reads.
