### ISSUE TITLE
Memory leak in fill_orphan

### ISSUE THREAD

**Issue by rvarki** [maxrossi91/moni-align#43]
Hi Max,

There is a memory leak in fill_orphan which I cannot figure out how to fix. The leak appears in this line according to valgrind:

https://github.com/maxrossi91/moni-align/blob/0d88231b96b994a93a57e49504abc837f7acf246/include/aligner/aligner_ksw2.hpp#L2553

If I understand the valgrind report correctly, the leak happens in the ksw_backtrack function that is called by the ksw_extz2_sse function. I have looked at the fill_orphan function and the ksw_extz2_sse function quite a bit and everything to me seems like it should be allocated/deallocated correctly. With the develop branch and the test data, you should be able to reproduce. I have  included the valgrind report on the test data. 

==3132527== Memcheck, a memory error detector
==3132527== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3132527== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==3132527== Command: /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2 ../data/mouse/index/mouse -1 ../data/mouse/reads/mouse.chr19.R1.fastq -2 ../data/mouse/reads/mouse.chr19.R2.fastq -t 1 -b 512 -A 2 -B 4 -O 4,13 -E 2,1 -L 100 -l 25 -w 50 -v 50 -x 500 -y 100 -D 50.0 -S 5000 -F 0.005 -o ../data/mouse/output/mouse.sam
==3132527== 
[INFO] 17:03:52 - Message: Construction of the aligner
[INFO] 17:03:53 - Message: Loading the matching statistics index
[INFO] 17:03:55 - Message: Matching statistics index loading complete
[INFO] 17:03:55 - Message: Memory peak:  0
[INFO] 17:03:55 - Message: Elapsed time (s):  2.12112
[INFO] 17:03:55 - Message: Loading random access file: ../data/mouse/index/mouse.plain.slp
[INFO] 17:03:55 - Message: Random access loading complete
[INFO] 17:03:55 - Message: Memory peak:  0
[INFO] 17:03:55 - Message: Elapsed time (s):  0.458695
[INFO] 17:03:55 - Message: Loading fasta index file: ../data/mouse/index/mouse.ldx
[INFO] 17:03:55 - Message: Fasta index loading complete
[INFO] 17:03:55 - Message: Memory peak:  0
[INFO] 17:03:55 - Message: Elapsed time (s):  0.011773
[INFO] 17:03:55 - Message: Initialize the local aligner
[INFO] 17:03:55 - Message: Local aligner initialization complete
[INFO] 17:03:55 - Message: Memory peak:  0
[INFO] 17:03:55 - Message: Elapsed time (s):  0.00134444
[INFO] 17:03:55 - Message: Minimum MEM length:  25
[INFO] 17:03:55 - Message: Memory peak:  0
[INFO] 17:03:55 - Message: Elapsed time (s):  2.62384
[INFO] 17:03:55 - Message: Processing patterns
[INFO] 17:03:55 - Message: Output file:  ../data/mouse/output/mouse.sam
[INFO] 17:04:06 - Message: Number of high quality samples processed so far:  504
[INFO] 17:04:11 - Message: Number of high quality samples processed so far:  1009
[INFO] 17:04:11 - Message: Insertion size estimation complete!
[INFO] 17:04:11 - Message: Number of high quality samples:  1009
[INFO] 17:04:11 - Message:                           Mean:  197.902
[INFO] 17:04:11 - Message:                       Variance:  11051.8
[INFO] 17:04:11 - Message:                Sample Variance:  11062.8
[INFO] 17:04:11 - Message:             Standard Deviation:  105.128
[INFO] 17:05:29 - Message: Number of aligned reads:  4982 / 5000
[INFO] 17:05:29 - Message:    Alignment statistics 
[INFO] 17:05:29 - Message:        Processed reads:  5000
[INFO] 17:05:29 - Message:          Aligned reads:  4982
[INFO] 17:05:29 - Message:           Orphan reads:  1
[INFO] 17:05:29 - Message: Orphan recovered reads:  1
[INFO] 17:05:29 - Message: Memory peak:  0
[INFO] 17:05:29 - Message: Elapsed time (s):  94.1305
[INFO] 17:05:29 - Message: Timing variable 0 :          74.7573 	( Seed extraction )
[INFO] 17:05:29 - Message: Timing variable 1 :          8.43397 	( Chaining )
[INFO] 17:05:29 - Message: Timing variable 2 :          8.44904 	( Chain alignment )
[INFO] 17:05:29 - Message: Timing variable 3 :          2.47879 	( Chaining - Anchor extraction )
[INFO] 17:05:29 - Message: Timing variable 4 :          2.57988 	( Chaining - Dynamic Programming )
[INFO] 17:05:29 - Message: Timing variable 5 :          0.54803 	( Chaining - Chain position )
[INFO] 17:05:29 - Message: Timing variable 6 :          2.67832 	( Chaining - Backtracking )
[INFO] 17:05:29 - Message: Timing variable 7 :          0.0248875 	( Orphan recovery )
[INFO] 17:05:29 - Message: Timing variable 8 :          30.3876 	( Seed extraction - Seeds finding )
[INFO] 17:05:29 - Message: Timing variable 9 :          13.7204 	( Seed extraction - Seeds occurrences )
malloc_count ### exiting, total: 0, peak: 0, current: 0
==3132527== 
==3132527== HEAP SUMMARY:
==3132527==     in use at exit: 16 bytes in 1 blocks
==3132527==   total heap usage: 11,195,024 allocs, 11,195,023 frees, 2,039,357,057 bytes allocated
==3132527== 
==3132527== 16 bytes in 1 blocks are definitely lost in loss record 1 of 1
==3132527==    at 0x403A69F: malloc (vg_replace_malloc.c:308)
==3132527==    by 0x403CE65: realloc (vg_replace_malloc.c:836)
==3132527==    by 0x4E88AB: ksw_backtrack.isra.0.constprop.0 (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527==    by 0x4E9F01: ksw_extz2_sse (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527==    by 0x45FB1C: aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > >::fill_orphan(long long&, long long&, kseq_t const*, bool, sam_t*, bool) (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527==    by 0x469565: aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > >::paired_chain_orphan_score(aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > >::paired_alignment_t&, unsigned long, double, double, bool, long long, long long) (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527==    by 0x490681: aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > >::orphan_recovery(aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > >::paired_alignment_t&, double, double) (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527==    by 0x49D2F9: aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > >::align(kpbseq_t*, _IO_FILE*, _IO_FILE*) (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527==    by 0x49DC6F: statistics_t st_align<aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > > >(aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527==    by 0x49EA83: void dispatcher<aligner<seed_finder<PlainSlp<unsigned int, FixedBitLenCode<(unsigned char)0>, FixedBitLenCode<(unsigned char)0> >, moni_lcp<ri::sparse_sd_vector, ms_rle_string<ri::sparse_sd_vector, ri::huff_string>, thr_bv<ms_rle_string<ri::sparse_sd_vector, ri::huff_string> > > > > >(Args&) (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527==    by 0x40B6D0: main (in /blue/boucher/rvarki/Testing/moni-align/build/src/align/align_full_ksw2)
==3132527== 
==3132527== LEAK SUMMARY:
==3132527==    definitely lost: 16 bytes in 1 blocks
==3132527==    indirectly lost: 0 bytes in 0 blocks
==3132527==      possibly lost: 0 bytes in 0 blocks
==3132527==    still reachable: 0 bytes in 0 blocks
==3132527==         suppressed: 0 bytes in 0 blocks
==3132527== 
==3132527== For lists of detected and suppressed errors, rerun with: -s
==3132527== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by rvarki** [comment]
I think I figured it out. We were not freeing the memory of the cigar string.

**Comment by maxrossi91** [comment]
I see. Yes, that might have caused some memory issues. Thanks for handling it.
